### ISSUE TITLE
Bottom corners of the window are square

### ISSUE THREAD

**Issue by nriley** [lapcat/Bonjeff#3]
I was able to fix a similar issue in my own app by making the root view layer-backed.

**Comment by Kentzo** [comment]
Doesn't layer-backing ruins font aliasing?

**Comment by nriley** [comment]
It did at one point, but not in years. I just checked on my app and I get full subpixel AA in that window.

**Comment by lapcat** [comment]
Fixed by making the window content view layer-backed. Thanks!
