### ISSUE TITLE
Wide-area Bonjour domains are empty

### ISSUE THREAD

**Issue by nriley** [lapcat/Bonjeff#4]
See attached for a comparison on my Mac.

![bonjeff vs bonjour browser](https://user-images.githubusercontent.com/68303/31363789-d6282954-ad2e-11e7-9dcd-cea079351a1a.png)

**Comment by lapcat** [comment]
Could you run Bonjeff with Console open and see if there's any log output?

**Comment by lapcat** [comment]
This bug should be fixed in Bonjeff 1.0.1. Can anyone verify this?

**Comment by nriley** [comment]
Yup, works for me — actually more info than Bonjour Browser now! Sorry for the lack of followup earlier.

![bonjeff 2](https://user-images.githubusercontent.com/68303/31510561-e70198ac-af52-11e7-8153-88ca0317e5d8.png)
