### ISSUE TITLE
Automatically resolving all services is a bad idea

### ISSUE THREAD

**Issue by lilyball** [lapcat/Bonjeff#6]
It looks like you're automatically resolving all services. This is a rather bad idea because it's going to produce a veritable storm of unnecessary network activity on any network with a decent number of services.

A good rule of thumb here is "would this be detrimental to the network if someone launched the app on Apple's internal network?" (where, as you can imagine, there are a lot of Apple devices advertising services)

**Comment by lapcat** [comment]
If necessary I could create a preference. I originally wrote the app for my own testing on my own network, and I personally want everything to resolve without having to manually expand the items.

Do you know empirically that this is an issue? I thought mDNS had some built-in throttling? With everyone nowadays streaming music and video and chatting on multiple internet services constantly, how does this compare in network traffic?

**Comment by lilyball** [comment]
When I released the first version of Rendezevous Browser I got emails from 2 different Apple employees (one of them being Stuart Cheshire, inventor of Bonjour) that both suggested I stop auto-resolving services because it was problematic on Apple's network.

Don't forget, the problem scenario here isn't just one person running the app on the network, it's the app becoming popular and many people running it.

**Comment by lapcat** [comment]
Ok, I think I've come up with a decent algorithm that doesn't require a Preference (which I'm trying to avoid as long as possible):

1. Implement https://github.com/lapcat/Bonjeff/issues/5 "Save collapsed state of outline view nodes".
2. By default, expand new domains.
3. By default, do not expand new service types.
4. By default, a new service will match the expanded or collapsed state of its service type.
5. Only resolve a service when it's expanded.

Thus by default there is no resolving unless the user deliberately expands nodes. I don't want to artificially restrict use cases though, so if someone within Apple decides to option-click the root and leave everything expanded, that would be an internal matter of crime and punishment.

Thoughts?

**Comment by lilyball** [comment]
(4) means if I expand a service type with 500 services it will start resolving 500 services?

**Comment by lapcat** [comment]
> (4) means if I expand a service type with 500 services it will start resolving 500 services?

No. Any services found before the service type is expanded inherit the collapsed state of the service type. Only new services found after the service type is expanded will inherit the new expanded state.

The idea here is that when you're testing with the app and leave it running, you're often particularly interested in new services getting published, which is why I want to auto-resolve those. Otherwise it gets annoying when you have to manually expand while you're watching. For any old services, you'd have to manually expand them to make them resolve (and leave them expanded to auto-resolve in the future).

**Comment by lilyball** [comment]
You shouldn't even be searching for a service type at all until it's expanded. Again, imagine running this on a network with 100 service types that have 500 services each.

My recommendation would be the following:

1. Remember the expansion state of domains, defaulting `local.` to expanded and wide-area domains to not expanded.
2. Remember the expansion state of services, defaulting to not expanded.
3. Don't resolve any service types unless they're expanded.
4. Remember the expansion state of services, defaulting to not expanded.
5. Don't resolve any services unless they're expanded.

That way if you're testing you only have to expand the service you're interested in once, and if it goes away and comes back it will stay expanded.

The only "problem" here is if you're testing a case where you're constantly generating services with never-before-seen names, but that should be a very rare thing to be doing because service names are usually generated in a predictable fashion.

**Comment by lapcat** [comment]
> You shouldn't even be searching for a service type at all until it's expanded.

Bonjour Browser searches collapsed service types at launch. It even shows the number of services on the right. I don't want to make Bonjeff more restricted than Bonjour Browser, I want to make it less restricted.

Networking has advanced quite a bit in the past 15 years, and I don't believe we have to be as ultra-conservative anymore. I've taken to heart the idea of not auto-resolving everything, but not auto-resolving anything seems overly restrictive. The data used by mDNS requests is pretty austere compared to everything else running through networks. I want to avoid network problems of course, but it's not a goal of mine to absolutely minimize the number of packets used.

**Comment by lilyball** [comment]
> Bonjour Browser searches collapsed service types at launch. It even shows the number of services on the right.

Hmm, looks like you're right, I must have mis-remembered that. I'm a little surprised that behavior was deemed ok for Apple's network, but if that's what Bonjour Browser has been doing, then I guess that's fine. Just don't auto-resolve the services themselves.
